name: Build Linux packages & prepare release
on: workflow_dispatch

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_source_archive:
    name: Build source archive
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Parse version number
        run: |
          VERSION=$(sed -En 's/^Version:[[:space:]]*(.*)/\1/p' rpm/run0edit.spec)
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Create source archive
        run: |
          mkdir -p "run0edit-$VERSION"
          find . -maxdepth 1 -type f '!' -name '.*' -execdir cp '{}' "run0edit-$VERSION/" ';'
          tar -cvf "run0edit-$VERSION.tar.gz" "run0edit-$VERSION"

      - name: Upload source as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: source-archive
          path: run0edit-*.tar.gz

  build_rpm:
    name: Build RPM package
    needs: build_source_archive
    runs-on: ubuntu-24.04
    container:
      image: fedora@sha256:aa7befe5cfd1f0e062728c16453cd1c479d4134c7b85eac00172f3025ab0d522 # v42
    steps:
      - name: Install dependencies
        run: |
          dnf install -y nodejs python3 python3-devel rpmdevtools rpmlint
          rpmdev-setuptree

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false

      - name: Modify RPM spec to use local source
        run: sed -Ei '/^Source0:/s/https:\/\/.*/%{name}-%{version}.tar.gz/' rpm/run0edit.spec

      - name: Retrieve source archive
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: source-archive
          path: ~/rpmbuild/SOURCES

      - name: Run rpmlint on RPM spec
        run: rpmlint rpm/run0edit.spec

      - name: Run rpmbuild on RPM spec
        run: rpmbuild -ba -v rpm/run0edit.spec

      - name: Upload SRPM as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: srpm
          path: ~/rpmbuild/SRPMS/run0edit-*.src.rpm
          if-no-files-found: error

      - name: Upload RPM as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: rpm
          path: ~/rpmbuild/RPMS/noarch/run0edit-*.noarch.rpm
          if-no-files-found: error

  build_deb:
    name: Build .deb package
    needs: build_rpm
    runs-on: ubuntu-24.04
    steps:
      - name: Optimize build times
        shell: bash
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update
          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf

      - name: Retrieve RPM
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: rpm

      - name: Convert .rpm to .deb
        run: |
          sudo apt update
          sudo apt install -y alien
          sudo alien -dkv run0edit-*.noarch.rpm

      - name: Upload .deb as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: deb
          path: run0edit_*.deb

  release:
    name: Release
    needs: [build_source_archive, build_rpm, build_deb]
    if: github.triggering_actor == 'HastD'
    runs-on: ubuntu-24.04
    permissions:
      contents: write # necessary to create release
    steps:
      - name: Retrieve all artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0

      - name: Create draft release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          draft: true
          files: |
            run0edit/run0edit
            source-archive/run0edit-*.tar.gz
            deb/run0edit_*.deb
            rpm/run0edit-*.noarch.rpm
            srpm/run0edit-*.src.rpm
          token: ${{ secrets.RUN0EDIT_ACCESS_TOKEN }}
